# Define the Racket executable
RACKET = racket

# Define the flags for running Racket
RACKET_FLAGS = -tm

# Define the name of your Racket source file
SRC_FILE = practical_2.rkt

# Define the default target
.DEFAULT_GOAL := run

# Define the target for running your Racket code
run:
	$(RACKET) $(RACKET_FLAGS) $(SRC_FILE)
